/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("advent.of.code.kotlin.kotlin-application-conventions")
}

dependencies {
    implementation(project(":utilities"))
    implementation("org.junit.jupiter:junit-jupiter:5.4.2")
}
